title: Navneet Kaur
logo: /assets/img/logo.png
description: I am a software developer. Working on Spring MVC Human Resource based solution product. I have experience of web application development in Java and Angular. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
