title: Navneet Kaur
logo: /assets/img/logo.png
description: Software Developer | Working on Spring MVC hybernate based web applications | Angular based application development
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
